meta_product_name: "Talentum"
meta_title: "Talentum - The social media for art"
meta_description: "Talentum is connecting artists with partners and art lovers around the world!"
meta_image: "cover.png"
